thymeleaf:
  cache: false
  prefix: classpath:/templates/
  suffix: .html
  encoding: UTF-8
  mode: HTML5=
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cptest?serverTimezone=Asia/Taipei&characterEncoding=utf-8
    username: kiri
    password: mlsh6300264
  devtools:
    add-properties: false
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
server:
  port: 8080